# Application configuration for Spring Cloud Gateway with JWT authentication
server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - JwtAuthFilter
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: grade-service
          uri: http://localhost:8082
          predicates:
            - Path=/grades/**
        - id: course-service
          uri: http://localhost:8083
          predicates:
            - Path=/courses/**
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/teachers/**
        - id: schedule-service
          uri: http://localhost:8085
          predicates:
            - Path=/schedule/**


  main:
    web-application-type=reactive: